### ISSUE TITLE
Make sure every component has bindings to props from component it extends

### ISSUE THREAD

**Issue by souhe** [callstackincubator/rebolt#16]
For example:
- [x] FlatList - for example missing `onLayout`
- [x] DrawerLayoutAndroid - missing props from View
- [x] PickerIOS - missing props from View
- [x] ProgressbarAndroid - missing props from View
- [x] ProgressViewIOS - missing props from View
- [x] SnapshotViewIOS - missing props from View

**Comment by souhe** [comment]
For now, we have to duplicate code with those props for every new component interface. In almost every `.rei` file there is, for example, a line `~onLayout: RNEvent.NativeLayoutEvent.t => unit=?,`.
There is a helper(`Props.extendView`) which only simplifies a little implementation for `.re` files.

@knowbody @grabbou Do you have any ideas how we can improve this? Is this even possible?

**Comment by knowbody** [comment]
@souhe I can't see [`FlatList`](https://facebook.github.io/react-native/docs/flatlist.html) having `onLayout` prop.

**Comment by souhe** [comment]
@knowbody it should have. See the docs, FlatList has all the props from VirtualizedList and VirtualizedList has `onLayout` - https://facebook.github.io/react-native/docs/virtualizedlist#props
