### ISSUE TITLE
Implement Animated.createAnimatedComponent

### ISSUE THREAD

**Issue by grabbou** [callstackincubator/rebolt#20]
React Native allows any component to be enhanced with `Animated.createAnimatedComponent`. Doing so makes this component capable of handling styles that contain animated values and more.

The following is the Javascript API:

```js
const AnimatedIcon = Animated.createAnimatedComponent(Icon);
const app = () => <AnimatedIcon />;
```

Question is - how do we make this work from Reason without much additional code? Couldn't manage to get this working during my prototyping session. 

Would love to get @chenglou and @jordwalke opinion on that (or anyone else who is deep into ReasonReact).

**Comment by jordwalke** [comment]
I think some unsafe casts would be in order here. How would you write this in JS? Take whatever you would do in JS and implement it in Reason, but with unsafe casts `Obj.magic`. Then see how many of the unsafe casts you can remove.

**Comment by grabbou** [comment]
Jumping on Skype with Jared today will try to get his help on solving this. Meanwhile, closing as there's no interest in using it so far. Hopefully by the time next person mentions this missing, we will have a complete solution in place.
