### ISSUE TITLE
ActivityIndicator

### ISSUE THREAD

**Issue by knowbody** [callstackincubator/rebolt#35]
- [ ] `size` - for example `` `exact(int) `` works only on Android, we could prevent breaking the app by setting the default to `` `small `` on iOS if exact is used

- [ ] `color` prop - in this case the color is just a string not a `String(color)`, everywhere else for color we use `String(color)`. This behaviour is inconsistent across a few other components that accept `color`, `backgroundColor`, etc. as props.

**Comment by codinglawyer** [comment]
I'd like to take this issue!
