### ISSUE TITLE
ProgressViewIOS & ProgressBarAndroid

### ISSUE THREAD

**Issue by knowbody** [callstackincubator/rebolt#37]
- [ ] `ProgressViewIOS` - why `progress` is not a required prop? IMO it should be required

**Comment by czystyl** [comment]
In the `ProggressBarAndoid`, the `progress` prop needs to be called with `indeterminate` prop. Where the `indeterminate`prop is only accepted when `styleAttr` is `Horizontal`.

Circle type of ProgressBarAndroid works like Activity indicator.

**Comment by knowbody** [comment]
I think we should make it only required on iOS then
