### ISSUE TITLE
Add Guides section

### ISSUE THREAD

**Issue by knowbody** [callstackincubator/rebolt#40]
This section is very valuable for people who are just starting off, either with Rebolt or with ReasonML in general. Please comment on this issue with topics of the guides that you would like to see.

- [ ] Animation guides
- [x] get started with `rebolt-navigation` (but I think this could also live in the `rebolt-navigation`'s docs, we could have some simple guide here as well)
- [ ] add some section about using refs (#5)

**Comment by knowbody** [comment]
as @grabbou mentioned here: https://twitter.com/grabbou/status/1013762607940079616

- Animation guides
- get started with `rebolt-navigation` (but I think this could also live in the `rebolt-navigation`'s docs, we could have some simple guide here as well)

**Comment by knowbody** [comment]
@souhe will you find some time today to write about the `ref`s section?

@grabbou any chance you could do Animation guides?

**Comment by grabbou** [comment]
There's already a nice introduction to Animated under its documentation that highlights some usages of the API rather than just explaining the methods available. Maybe we should consider moving it?
