### ISSUE TITLE
Use new @bs.deriving abstract 

### ISSUE THREAD

**Issue by czystyl** [callstackincubator/rebolt#47]
Some of the components and API's uses the old object API that is deprecated by [BuckedScript doc](https://bucklescript.github.io/docs/en/object-deprecated). 
Instead of using deprecated object use the new [`[@bs.deriving abstract]`](https://bucklescript.github.io/docs/en/object) and [`[@bs.deriving jsConverter]`](https://bucklescript.github.io/docs/en/generate-converters-accessors)

List of component contain depricated API:
* [ ] flatList
* [ ] animatedRe
* [ ] cameraRoll
* [ ] scrollView
* [ ] sectionList
* [ ] textInput
* [ ] touchableHighlight
* [ ] touchableOpacity
* [ ] viewPagerAndroid
* [ ] imagePickerIOS
* [ ] linking
* [ ] panResponder
* [ ] utilsRN
* [ ] RNEvent
* [ ] events
* [ ] permissionsAndroid

Feel free to update that list.

**Comment by knowbody** [comment]
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by knowbody** [comment]
- [ ] animatedRe
- [ ] cameraRoll
- [ ] scrollView
- [ ] sectionList
- [ ] textInput
- [ ] touchableHighlight
- [ ] touchableOpacity
- [ ] viewPagerAndroid
- [ ] imagePickerIOS
- [ ] linking
- [ ] panResponder
- [ ] utilsRN
- [ ] RNEvent

**Comment by grabbou** [comment]
@czystyl are you willing on working on that one? Would be great and sounds like an easy contribution. Can I count on you to open this issue against `bs-react-native` and send a PR? We are planning next release today, would be great to ship it.

**Comment by czystyl** [comment]
Moved to https://github.com/reasonml-community/bs-react-native/issues/240
