### ISSUE TITLE
Utils for converting JS object into the Reason record.

### ISSUE THREAD

**Issue by czystyl** [callstackincubator/rebolt#49]
* [ ] events
* [ ] permissionsAndroid

**Comment by knowbody** [comment]
@czystyl could you please add more info to this issue, and your thoughts on how this can be implemented, maybe some resources useful to the issue?

**Comment by czystyl** [comment]
I'd like to use `[@bs.deriving jsConverter]`

**Comment by czystyl** [comment]
I'd like to use `[@bs.deriving jsConverter]`

**Comment by czystyl** [comment]
Closed in favour of #47
