### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by souhe** [callstackincubator/rebolt#5]
- [x] add methods documentation to every component which have any - `FlatList`, `ScrollView`, `TextInput`, `TauchableOpacity`, `WebView`. For example, there is no info about `scrollTo` method in FlatList docs - https://rebolt.callstack.com/docs/flat-list.html
- [x] write docs to APIs
- [x] Fix every variant list in docs. Currently we use triple backtick to make it possible to use \` in variant name, which looks ugly. See for example ActivityIndicator docs.
We can use this instead:
```
`` `variantName ``
```

**Comment by grabbou** [comment]
I am going to work on documentation for Animated and Easing. Going to start `WIP` branch as soon as possible.
