### ISSUE TITLE
Support for react-native-web

### ISSUE THREAD

**Issue by kgoggin** [callstackincubator/rebolt#52]
I'm working on an app using Reason that will have a native and a web build, using [react-native-web](https://github.com/necolas/react-native-web) to create components that can be reused in both environments. RNW does a great job of matching the overall RN API, so everything _mostly_ just works when we use Rebolt for our RN bindings. However, there are a few edge cases where the API is not a 1:1 match. These edge cases can be grouped into two overall categories:

 1. *Web-only props.* These are few and far between, and well-documented by RNW. The biggest need I have right now is to be able to pass an `accessibilityRole` to a `<View/>` ([docs](https://necolas.github.io/react-native-web/storybook/?selectedKind=Components&selectedStory=View&full=0&addons=0&stories=1&panelRight=0)). RNW uses this prop to help determine the underlying DOM node that gets rendered so it's important for accessibility.
 2. *Web-only CSS rules.* There's a fair amount of CSS that's available on the web but not in RN. Some of the things I've encountered so far are `outline`, `cursor`, and `userSelect`. 

Of course the most straightforward approach would be to just add the needed props and CSS rules to the bindings, but you're then inheriting the need to keep up with RNW's API in addition to RN's, so I realize that's not a decision to take lightly. Beyond that scenario, there are a couple of others I've considered:

 * For CSS rules, expose more of the internals of the Style module, which would allow library consumers to add their own rules. Currently this is not possible because the API is limited via the interface, but it'd be pretty simple to expose some of the encoders and things like [`stringStyle`](https://github.com/callstackincubator/rebolt/blob/master/src/style.re#L80). Then users could use whatever web CSS they wanted on their own, and be responsible for the upkeep themselves. The downside is that with more of the internals exposed publicly, there's more opportunity for breaking changes.
 * For components requiring web-only props, I've played around with binding to RNW's `createElement`, which lets me create my own components that conform to RNW's styling framework. But, this isn't as ideal as I then have to swap out the implementation of specific components based on the Platform.

I'm certainly open to other approaches as well! Or, if this isn't a priority for your project right now, I'm okay with going back to running my own fork where I add what I need myself. But I'd love to discuss how we might be able to support this, because I think the combo of Reason + RN + RNW is a really solid one for building outstanding apps! Thanks!

**Comment by knowbody** [comment]
As we want to make Rebolt very modular, I'm wondering if we could work on this as a separate module that could be added to rebolt projects but it doesn't have to be a core part of Rebolt. What do you think?

**Comment by kgoggin** [comment]
Hmm, that's an interesting idea. How would you foresee that working for something like components that need a web-specific prop? Would you just have a separate module that contained clones of the native components with the props added? 

The Style.re module could be a little easier - just create a `StyleWeb.re` and include the existing module, then add the web-specific style rules. Though again you'd run into the issue of the internals not being exposed, so maybe you'd break those into a separate module that could also be used in the separate StyleWeb.

**Comment by knowbody** [comment]
@kgoggin I would like to leave the decision on how this can be implemented for you. As I said, from my perspective the best thing to do would be to have it in a modular way and have something like `rebolt-native-web` as a separate package, so people who want to use it can just add it to their project and it would work out of the box. What do you think?

**Comment by grabbou** [comment]
Closing this issue as we have moved all the code to [`bs-react-native`](https://github.com/reasonml-community/bs-react-native). Please submit your ticket there once again and we will be able to take it forward.

Thank you for cooperating on `rebolt` with us and pursuing the idea of web support. This is definitely something we are interested in seeing.
